name: second_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter_web: any
  scoped_model: ^1.0.1
  http: ^0.12.0+1
  shared_preferences: ^0.5.2
  rxdart: ^0.21.0
  # map_view: ^0.0.14
  map_view:
    git:
      url: git://github.com/Eimji/flutter_google_map_view.git
  location: ^2.3.3
  # image_picker: ^0.6.0+8
  mime: ^0.9.6+2
  url_launcher: ^5.0.2
  google_maps_flutter: ^0.5.15

dev_dependencies:
  flutter_web_test: any
  build_runner: any
  build_web_compilers: any
  test: ^1.3.4
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png" 
  adaptive_icon_background: "#FFFAFAFA"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # uses-material-design: true

dependency_overrides:
  flutter_web:
      git:
        url: https://github.com/flutter/flutter_web
        path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

